[package]
name = "contact"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
email_address = "0.2.0"
rusqlite = "0.26.0"
